# Generated by Django 3.0.8 on 2021-10-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_bleeding'),
        ('users', '0002_auto_20210930_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cycles',
        ),
        migrations.AddField(
            model_name='user',
            name='bleedings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bleedings', to='tracking.Bleeding'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categories', to='tracking.Category'),
        ),
    ]
