# Generated by Django 3.0.8 on 2021-10-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20211010_1554'),
        ('users', '0003_auto_20211010_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bleedings',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bleedings', to='tracking.Bleeding'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_categories', to='tracking.Category'),
            preserve_default=False,
        ),
    ]
