# Generated by Django 3.0.8 on 2021-10-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211010_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bleedings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
    ]
