# Generated by Django 3.0.8 on 2021-10-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_trackable_user'),
        ('records', '0003_auto_20211017_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.ManyToManyField(blank=True, null=True, related_name='logs', to='tracking.Trackable'),
        ),
    ]
