# Generated by Django 3.0.8 on 2021-11-22 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_flow_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0004_auto_20211017_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.ManyToManyField(blank=True, related_name='logs', to='tracking.Trackable'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
