# Generated by Django 3.0.8 on 2021-10-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210930_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
