# Generated by Django 3.0.8 on 2021-10-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bleeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
