# Generated by Django 3.0.8 on 2021-10-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_bleeding_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bleeding',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracking.Category'),
        ),
    ]
