# Generated by Django 3.0.8 on 2021-10-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211010_1711'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0007_auto_20211010_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bleeding',
            name='Trackable',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bleeding',
        ),
    ]
