# Generated by Django 3.0.8 on 2021-11-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_trackable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='level',
            field=models.CharField(choices=[('0', 'Spotting'), ('1', 'Low'), ('2', 'Medium'), ('3', 'Heavy'), ('4', 'Very Heavy')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
